name: Applications
on:
  workflow_dispatch:
    inputs:
      scipy:
        required: true
        default: true
        type: boolean
      tasmotizer:
        required: true
        default: true
        type: boolean
      xonsh:
        required: true
        default: true
        type: boolean
      ssh-mitm:
        required: true
        default: true
        type: boolean

jobs:
  Test:
    runs-on: ubuntu-22.04  # 替换为 ubuntu-22.04 或 ubuntu-latest
    strategy:
      matrix:
        version: ['2.7', '3.7', '3.9']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version }}

    - name: Test scipy
      if: ${{ inputs.scipy }}
      run: |
        python -m python_appimage build app applications/scipy                 \
                                            --python-version=2.7               \
                                            --python-tag=cp27-cp27mu
        test -e scipy-x86_64.AppImage
        ./scipy-x86_64.AppImage -c 'import numpy, pandas, scipy'

    - name: Test tasmotizer
      if: ${{ inputs.tasmotizer }}
      run: |
        python -m python_appimage build app applications/tasmotizer            \
                                            --linux-tag=manylinux1_x86_64      \
                                            --python-version=3.9
        test -e tasmotizer-x86_64.AppImage

    - name: Test xonsh
      if: ${{ inputs.xonsh }}
      run: |
        python -m python_appimage build app applications/xonsh
        test -e xonsh-x86_64.AppImage
        ./xonsh-x86_64.AppImage -c 'import xonsh'

    - name: Test ssh-mitm
      if: ${{ inputs.ssh_mitm && (matrix.version == '3.9') }}
      run: |
        python -m python_appimage build app applications/ssh-mitm
        test -e ssh-mitm-x86_64.AppImage
        ./ssh-mitm-x86_64.AppImage --help
