name: Applications
on:
  workflow_dispatch:
    inputs:
      scipy:
        required: true
        default: true
        type: boolean
      tasmotizer:
        required: true
        default: true
        type: boolean
      xonsh:
        required: true
        default: true
        type: boolean
      ssh-mitm:
        required: true
        default: true
        type: boolean

jobs:
  Test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: ['3.7', '3.9']  # 移除 2.7，仅保留 3.7 和 3.9

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential zlib1g-dev libncurses5-dev \
                                libgdbm-dev libnss3-dev libssl-dev libreadline-dev \
                                libffi-dev curl libbz2-dev
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version }}
    - name: Install python_appimage
      run: pip install --upgrade python-appimage

    - name: Test scipy
      if: ${{ inputs.scipy }}
      run: |
        python -m python_appimage build app applications/scipy                 \
                                            --python-version=${{ matrix.version }}
        test -e scipy-x86_64.AppImage
        ./scipy-x86_64.AppImage -c 'import numpy, pandas, scipy'

    - name: Test tasmotizer
      if: ${{ inputs.tasmotizer }}
      run: |
        python -m python_appimage build app applications/tasmotizer            \
                                            --linux-tag=manylinux1_x86_64      \
                                            --python-version=3.9
        test -e tasmotizer-x86_64.AppImage

    - name: Test xonsh
      if: ${{ inputs.xonsh }}
      run: |
        python -m python_appimage build app applications/xonsh
        test -e xonsh-x86_64.AppImage
        ./xonsh-x86_64.AppImage -c 'import xonsh'

    - name: Test ssh-mitm
      if: ${{ inputs.ssh_mitm && (matrix.version == '3.9') }}
      run: |
        python -m python_appimage build app applications/ssh-mitm
        test -e ssh-mitm-x86_64.AppImage
        ./ssh-mitm-x86_64.AppImage --help
